<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container0wz1px5\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container0wz1px5/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container0wz1px5.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container0wz1px5\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container0wz1px5\appDevDebugProjectContainer([
    'container.build_hash' => '0wz1px5',
    'container.build_id' => '0a75ba31',
    'container.build_time' => 1588835100,
], __DIR__.\DIRECTORY_SEPARATOR.'Container0wz1px5');
